services:
  - type: web
    name: ravon-ai-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    healthCheckPath: "/ping"
    envVars:
      - key: WEB_CONCURRENCY
        value: "0"
      - key: NODE_ENV
        value: "production"
