ALTER TABLE test_words ADD COLUMN IF NOT EXISTS lang TEXT DEFAULT 'en';
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS target_lang TEXT DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_lang TEXT DEFAULT 'en';
